import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { BookingContextProvider } from './booking-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <BookingContextProvider>{children}</BookingContextProvider>
      </body>
    </html>
  )
}
